SELECT wo.[Workorderno]
      ,wo.[Item_Code]
      ,wo.[Wc_Code]
      ,wo.[Plan_Qty]
      ,wo.[Plan_Unit]
      ,wo.[Plan_Date]
      ,wo.[Prd_Date]
      ,wo.[Wo_Status]
      ,wo.[Wo_Order]
      ,wo.[Plan_Starttime]
      ,wo.[Plan_Endtime]
      ,wo.[Prd_Starttime]
      ,wo.[Prd_Endtime]
      ,wo.[In_Qty_Main]
      ,wo.[Out_Qty_Main]
      ,wo.[Prd_Qty]
      ,wo.[Prd_Unit]
      ,wo.[Worker_CloseTime]
      ,wo.[Manager_CloseTime]
      ,wo.[Close_CancelTime]
      ,wo.[Wo_Req_No]
      ,wo.[Req_Seq]
      ,wo.[Mat_LotNo]
      ,wo.[Remark]
      ,wo.[Ins_Date]
      ,wo.[Ins_Emp]
      ,wo.[Up_Date]
      ,wo.[Up_Emp]
  FROM [TEAM4].[dbo].[WorkOrder] as wo

SELECT im.[Item_Code]
      ,im.[Item_Name]
      ,im.[Item_Name_Eng]
      ,im.[Item_Name_Eng_Alias]
      ,im.[Item_Type]
      ,im.[Item_Spec]
      ,im.[Item_Unit]
      ,im.[Level_1]
      ,im.[Level_2]
      ,im.[Level_3]
      ,im.[Level_4]
      ,im.[Level_5]
      ,im.[Item_Stock]
      ,im.[Lead_Time]
      ,im.[LotSize]
      ,im.[PrdQty_Per_Hour]
      ,im.[PrdQTy_Per_Batch]
      ,im.[Cavity]
      ,im.[Line_Per_Qty]
      ,im.[Shot_Per_Qty]
      ,im.[Dry_GV_Qty]
      ,im.[Heat_GV_Qty]
      ,im.[Remark]
      ,im.[Use_YN]
      ,im.[Ins_Date]
      ,im.[Ins_Emp]
      ,im.[Up_Date]
      ,im.[Up_Emp]
  FROM [TEAM4].[dbo].[Item_Master] as im

SELECT ds.[Detail_Seq]
      ,ds.[User_ID]
      ,ds.[Workorderno]
      ,ds.[Prd_Starttime]
      ,ds.[Prd_Endtime]
      ,ds.[Prd_Qty]
      ,ds.[Ins_Date]
      ,ds.[Ins_Emp]
      ,ds.[Up_Date]
      ,ds.[Up_Emp]
  FROM [TEAM4].[dbo].[Emp_Allocation_History_Detail] as ds


  /****** 작업지시현황 ******/
  SELECT wo.[Workorderno]
    ,wo.[Wo_Status]
    ,ds.[User_ID]
    , im.[Item_Code]
      ,im.[Item_Name]
      ,im.[Item_Unit]
      ,wo.[Prd_Qty]
      ,wo.[Prd_Starttime]
      ,wo.[Prd_Endtime]
  FROM [TEAM4].[dbo].[WorkOrder] wo
  JOIN [Item_Master] as im ON im.[Item_Code] = wo.[Item_Code]
  JOIN [Emp_Allocation_History_Detail] as ds ON ds.[Workorderno] = wo.[Workorderno];

  -- TODO : 작업장 코드 별로 수정